# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
    imports = [
        <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

    boot = {
        supportedFilesystems = [ "btrfs" ];
        initrd = {
            supportedFilesystems = [ "btrfs" ];
            availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
            kernelModules = [ ];
        };
        kernelModules = [ "kvm-amd" ];
        extraModulePackages = [ ];
    };

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/1436a8d5-fbfc-4c46-941b-28b2eddc3b7a";
        fsType = "btrfs";
        options = [ "subvol=@" ];
    };

    fileSystems."/home" = {
        device = "/dev/disk/by-uuid/1436a8d5-fbfc-4c46-941b-28b2eddc3b7a";
        fsType = "btrfs";
        options = [ "subvol=@home" ];
    };

    fileSystems."/nix" = {
        device = "/dev/disk/by-uuid/1436a8d5-fbfc-4c46-941b-28b2eddc3b7a";
        fsType = "btrfs";
        options = [ "subvol=@nix" ];
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/CC42-1ECC";
        fsType = "vfat";
    };

    swapDevices = [
        { device = "/dev/disk/by-uuid/df0c60c6-5b1f-46ca-a417-418f4ab1ab72"; }
    ];

    nix.maxJobs = lib.mkDefault 16;
}
