# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }: {
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = [
    { name = "cryptnix";
      device = "/dev/disk/by-uuid/e24e48fa-bf01-41ee-85da-081445272e4c";
      allowDiscards = true;
    }
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3e2292cb-9d4d-4659-b059-b43e89a2feea";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F63A-8AE9";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/0b066fa6-e35c-da41-8041-a22d4d8ab50d";
        encrypted.label = "nixswap";
        randomEncryption.enable = true; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
