# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ata_piix" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."cryptnix" =
    { device = "/dev/disk/by-uuid/a12f7324-d45e-4f47-97f2-4c6ff7a1c495";
      allowDiscards = true;
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e733bd9b-367f-4e5e-8ef8-c235c4b0add9";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e733bd9b-367f-4e5e-8ef8-c235c4b0add9";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e733bd9b-367f-4e5e-8ef8-c235c4b0add9";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0F68-9FD3";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/32e30ff6-a9d3-c24b-96d8-6533980e70b9";
        encrypted.label = "cryptswap";
        randomEncryption.enable = true;
      }
    ];

  nix.maxJobs = lib.mkDefault 2;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
