# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptnix";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@" ];
    };

  boot.initrd.luks.devices = [
    { name = "cryptnix";
      device = "/dev/disk/by-uuid/d46b9e6f-3f2b-4398-be5a-33f3b36be19a";
      allowDiscards = true;
    }
  ];

  fileSystems."/home" =
    { device = "/dev/mapper/cryptnix";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/cryptnix";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7D17-CC90";
      fsType = "vfat";
    };

  fileSystems."/mnt/zshare" =
    { device = "//fmsnsggss002.amr.corp.intel.com/map";
      fsType = "cifs";
      options = let
        # this line prevents hanging on network split
        automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";

      in ["${automount_opts},credentials=/etc/nixos/smb-secrets"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/4be40df6-9a56-0c49-8b62-14ba7516d91b";
        encrypted.label = "nixswap";
        randomEncryption.enable = true; }
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
