# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptnix";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@" ];
    };

  boot.initrd.luks.devices = [
    { name = "cryptnix";
      device = "/dev/disk/by-uuid/d46b9e6f-3f2b-4398-be5a-33f3b36be19a";
      allowDiscards = true;
    }
  ];

  fileSystems."/home" =
    { device = "/dev/mapper/cryptnix";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/cryptnix";
      fsType = "btrfs";
      options = [ "discard,noatime,compress=lzo,subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7D17-CC90";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f7c2105e-d073-4be7-ac4b-8994175358f9"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
